### PR TITLE
nameroot enhancements

### PR DESCRIPTION
**Pull request by undu**
Update patch to upstream, generate nameroot correctly, along with nameext.
Also no need to generate it for Directories, as per specification: http://www.commonwl.org/v1.0/Workflow.html#Directory

Do not merge yet, tests are still not fixed and I'd like to add some more too to test this piece of code.

### CODE REVIEW

**Comment by undu** [comment]
This is for https://github.com/common-workflow-language/cwltool/pull/338

**Comment by undu** [comment]
weird, tests failed because it cannot launch the linter. Unit tests pass though.

**Comment by kapilkd13** [comment]
Thanks @undu for this :smiley: . We can ignore the Appveyor CI (as I set it up for test local changes only.) I guess pylint is causing problem in this line https://travis-ci.org/kapilkd13/cwltool/jobs/240981163#L184

**Comment by undu** [comment]
@mr-c asked to create a PR directly against upstream, it's https://github.com/common-workflow-language/cwltool/pull/420

**Pull request closed without merging**
